//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить звезду.
        /// </summary>
        internal static string AddAStar {
            get {
                return ResourceManager.GetString("AddAStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить созвездие из каталога?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveTheConstellationFromTheCatalog {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveTheConstellationFromTheCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить звезду из каталога?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveTheStarFromTheCatalog {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveTheStarFromTheCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите заменить данные?.
        /// </summary>
        internal static string AreYouSureYouWantToReplaceTheData {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToReplaceTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог созвездий:.
        /// </summary>
        internal static string CatalogOfConstellations {
            get {
                return ResourceManager.GetString("CatalogOfConstellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог планет:.
        /// </summary>
        internal static string CatalogOfPlanets {
            get {
                return ResourceManager.GetString("CatalogOfPlanets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог звёзд:.
        /// </summary>
        internal static string CatalogOfStars {
            get {
                return ResourceManager.GetString("CatalogOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить данные.
        /// </summary>
        internal static string ChangeTheData {
            get {
                return ResourceManager.GetString("ChangeTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить действие.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Созвездия.
        /// </summary>
        internal static string Constellations {
            get {
                return ResourceManager.GetString("Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подкорректировать ссылки.
        /// </summary>
        internal static string CorrectLinks {
            get {
                return ResourceManager.GetString("CorrectLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные были успешны добавлены.
        /// </summary>
        internal static string DataWasSuccessfullyAdded {
            get {
                return ResourceManager.GetString("DataWasSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склонение, град.мин:.
        /// </summary>
        internal static string Declination {
            get {
                return ResourceManager.GetString("Declination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склонение должно быть числом в диапазоне от -90 до 90 (дробная часть меньше 60).
        /// </summary>
        internal static string DeclinationMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("DeclinationMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить всё.
        /// </summary>
        internal static string DeleteEverything {
            get {
                return ResourceManager.GetString("DeleteEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите склонение.
        /// </summary>
        internal static string EnterTheDeclination {
            get {
                return ResourceManager.GetString("EnterTheDeclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите светимость.
        /// </summary>
        internal static string EnterTheLuminosity {
            get {
                return ResourceManager.GetString("EnterTheLuminosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите название.
        /// </summary>
        internal static string EnterTheName {
            get {
                return ResourceManager.GetString("EnterTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дайте название созведию.
        /// </summary>
        internal static string EnterTheNameOfConstellation {
            get {
                return ResourceManager.GetString("EnterTheNameOfConstellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите радиус.
        /// </summary>
        internal static string EnterTheRadius {
            get {
                return ResourceManager.GetString("EnterTheRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите прямое восхождение.
        /// </summary>
        internal static string EnterTheRightAscension {
            get {
                return ResourceManager.GetString("EnterTheRightAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите температуру.
        /// </summary>
        internal static string EnterTheTemperature {
            get {
                return ResourceManager.GetString("EnterTheTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите URI картинки.
        /// </summary>
        internal static string EnterTheURIOfImage {
            get {
                return ResourceManager.GetString("EnterTheURIOfImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите массу.
        /// </summary>
        internal static string EnterTheWeight {
            get {
                return ResourceManager.GetString("EnterTheWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите для поиска.
        /// </summary>
        internal static string EnterToSearch {
            get {
                return ResourceManager.GetString("EnterToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поля не должны быть пустыми.
        /// </summary>
        internal static string FieldsMustNotBeEmpty {
            get {
                return ResourceManager.GetString("FieldsMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерактив движения планет.
        /// </summary>
        internal static string InteractiveOfPlanetMovement {
            get {
                return ResourceManager.GetString("InteractiveOfPlanetMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход в интернет.
        /// </summary>
        internal static string InternetAccess {
            get {
                return ResourceManager.GetString("InternetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светимость.
        /// </summary>
        internal static string Luminosity {
            get {
                return ResourceManager.GetString("Luminosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светимость должна быть положительным числом.
        /// </summary>
        internal static string LuminosityMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("LuminosityMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светимость, Lo(= 3,827 * 10^26 Вт):.
        /// </summary>
        internal static string LuminosityOfStarLabelText {
            get {
                return ResourceManager.GetString("LuminosityOfStarLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта звёздного неба.
        /// </summary>
        internal static string MapOfStarrySky {
            get {
                return ResourceManager.GetString("MapOfStarrySky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наблюдательные данные.
        /// </summary>
        internal static string ObservationalData {
            get {
                return ResourceManager.GetString("ObservationalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус орбиты, *10^6 км.
        /// </summary>
        internal static string OrbitRadius {
            get {
                return ResourceManager.GetString("OrbitRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период обращения вокруг своей оси, дней.
        /// </summary>
        internal static string PeriodOfRotationAroundTheAxis {
            get {
                return ResourceManager.GetString("PeriodOfRotationAroundTheAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период ее обращения вокруг этого тела, суток.
        /// </summary>
        internal static string PeriodOfRotationAroundTheBody {
            get {
                return ResourceManager.GetString("PeriodOfRotationAroundTheBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снимки планет.
        /// </summary>
        internal static string PhotosOfPlanets {
            get {
                return ResourceManager.GetString("PhotosOfPlanets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физические характеристики.
        /// </summary>
        internal static string PhysicalCharacteristics {
            get {
                return ResourceManager.GetString("PhysicalCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планеты.
        /// </summary>
        internal static string Planets {
            get {
                return ResourceManager.GetString("Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Положение на звездной карте:.
        /// </summary>
        internal static string PositionOnTheStarMap {
            get {
                return ResourceManager.GetString("PositionOnTheStarMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первостепенные данные.
        /// </summary>
        internal static string PrimaryData {
            get {
                return ResourceManager.GetString("PrimaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус должен быть положительным числом.
        /// </summary>
        internal static string RadiusMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("RadiusMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус, км.
        /// </summary>
        internal static string RadiusOfPlanet {
            get {
                return ResourceManager.GetString("RadiusOfPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус, Ro(= 6,960 * 10^8 м):.
        /// </summary>
        internal static string RadiusOfStarLabelText {
            get {
                return ResourceManager.GetString("RadiusOfStarLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить созвездие из каталога.
        /// </summary>
        internal static string RemoveConstellationFromCatalog {
            get {
                return ResourceManager.GetString("RemoveConstellationFromCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить звезду из каталога.
        /// </summary>
        internal static string RemoveTheStarFromTheCatalog {
            get {
                return ResourceManager.GetString("RemoveTheStarFromTheCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямое восхождение, ч.мин:.
        /// </summary>
        internal static string RightAscension {
            get {
                return ResourceManager.GetString("RightAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямое восхождение должно быть положительным числом меньше 24 (дробная часть меньше 60).
        /// </summary>
        internal static string RightAscensionMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("RightAscensionMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить ссылку.
        /// </summary>
        internal static string SaveTheLink {
            get {
                return ResourceManager.GetString("SaveTheLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать ссылку.
        /// </summary>
        internal static string SelectTheLink {
            get {
                return ResourceManager.GetString("SelectTheLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звёзды.
        /// </summary>
        internal static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звёзды:.
        /// </summary>
        internal static string StarsAndTwoPoints {
            get {
                return ResourceManager.GetString("StarsAndTwoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица звёзд.
        /// </summary>
        internal static string TableOfStars {
            get {
                return ResourceManager.GetString("TableOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура должна быть положительным числом.
        /// </summary>
        internal static string TemperatureMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("TemperatureMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура, К:.
        /// </summary>
        internal static string TemperatureOfStarLabelText {
            get {
                return ResourceManager.GetString("TemperatureOfStarLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело, вокруг которого планета вращается.
        /// </summary>
        internal static string TheBodyAroundWhichThePlanetRotates {
            get {
                return ResourceManager.GetString("TheBodyAroundWhichThePlanetRotates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Созвездие было успешно удалено из каталога.
        /// </summary>
        internal static string TheConstellationHasBeenSuccessfullyRemovedFromTheCatalog {
            get {
                return ResourceManager.GetString("TheConstellationHasBeenSuccessfullyRemovedFromTheCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные были успешны заменены.
        /// </summary>
        internal static string TheDataWasSuccessfullyReplaced {
            get {
                return ResourceManager.GetString("TheDataWasSuccessfullyReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входящие звезды.
        /// </summary>
        internal static string TheIncludedStars {
            get {
                return ResourceManager.GetString("TheIncludedStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звезда была успешно удалена из каталога.
        /// </summary>
        internal static string TheStarHasBeenSuccessfullyRemovedFromTheCatalog {
            get {
                return ResourceManager.GetString("TheStarHasBeenSuccessfullyRemovedFromTheCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип звезды.
        /// </summary>
        internal static string TypeOfStar {
            get {
                return ResourceManager.GetString("TypeOfStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URI картинки:.
        /// </summary>
        internal static string URIOfImage {
            get {
                return ResourceManager.GetString("URIOfImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масса.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масса должна быть положительным числом.
        /// </summary>
        internal static string WeightMustBeAPositiveNumber {
            get {
                return ResourceManager.GetString("WeightMustBeAPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масса, *10^22 кг.
        /// </summary>
        internal static string WeightOfPlanet {
            get {
                return ResourceManager.GetString("WeightOfPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масса, Mo(= (1,98847 ± 0,00007) * 10^30 кг):.
        /// </summary>
        internal static string WeightOfStarLabelText {
            get {
                return ResourceManager.GetString("WeightOfStarLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
